config/routes.rb
AnswerDrift::Application.routes.draw do
  resources :balls
  root 'balls#index'

end

app/models/ball.rb
class Ball < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/balls_controller.rb
class BallsController < ApplicationController
  before_action :set_ball, only: [:show, :edit, :update, :destroy]

  # GET /balls
  # GET /balls.json
  def index
    @balls = Ball.all
  end

  # GET /balls/1
  # GET /balls/1.json
  def show
  end

  # GET /balls/new
  def new
    @ball = Ball.new
  end

  # GET /balls/1/edit
  def edit
  end

  # POST /balls
  # POST /balls.json
  def create
    @ball = Ball.new(ball_params)

    respond_to do |format|
      if @ball.save
        format.html { redirect_to @ball, notice: 'Ball was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ball }
      else
        format.html { render action: 'new' }
        format.json { render json: @ball.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /balls/1
  # PATCH/PUT /balls/1.json
  def update
    respond_to do |format|
      if @ball.update(ball_params)
        format.html { redirect_to @ball, notice: 'Ball was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ball.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /balls/1
  # DELETE /balls/1.json
  def destroy
    @ball.destroy
    respond_to do |format|
      format.html { redirect_to balls_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ball
      @ball = Ball.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ball_params
      params.require(:ball).permit(:colour)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balls_helper.rb
module BallsHelper
end

app/views/balls/_form.html.erb
<%= form_for(@ball) do |f| %>
  <% if @ball.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ball.errors.count, "error") %> prohibited this ball from being saved:</h2>

      <ul>
      <% @ball.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/balls/edit.html.erb
<h1>Editing ball</h1>

<%= render 'form' %>

<%= link_to 'Show', @ball %> |
<%= link_to 'Back', balls_path %>

app/views/balls/index.html.erb
<h1>Listing balls</h1>

<table>
  <thead>
    <tr>
      <th>Colour</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @balls.each do |ball| %>
      <tr>
        <td><%= ball.colour %></td>
        <td><%= link_to 'Show', ball %></td>
        <td><%= link_to 'Edit', edit_ball_path(ball) %></td>
        <td><%= link_to 'Destroy', ball, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ball', new_ball_path %>

app/views/balls/new.html.erb
<h1>New ball</h1>

<%= render 'form' %>

<%= link_to 'Back', balls_path %>

app/views/balls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Colour:</strong>
  <%= @ball.colour %>
</p>

<%= link_to 'Edit', edit_ball_path(@ball) %> |
<%= link_to 'Back', balls_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AnswerDrift</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>